namespace Jellyfish.Client.SendouInk.Core;

/// <summary>
///     API Constants
/// </summary>
public static class Constants
{
    /// <summary>
    ///     Weapon slugs (API) as key, alias as values
    ///     Please use uppercase and remove white chars for matching alias
    /// </summary>
    public static Dictionary<string, string[]> WeaponSlugs = new()
    {
        { "52-gal", ["50", ".52加仑", "52"] },
        { "52-gal-deco", ["51", ".52加仑装饰", "贴牌52"] },
        { "96-gal", ["80", ".96加仑", "96"] },
        { "96-gal-deco", ["81", ".96加仑装饰", "贴牌96"] },
        { "splattershot-pro", ["70", "顶尖射击枪", "精英枪", "蓝精英"] },
        { "forge-splattershot-pro", ["71", "顶尖射击枪联名", "贴牌精英枪", "黄精英"] },
        { "custom-splattershot-jr", ["11", "枫叶射击枪", "枫叶"] },
        { "sploosh-o-matic", ["0", "广域标记枪", "喇叭"] },
        { "neo-sploosh-o-matic", ["1", "广域标记枪新型", "贴牌喇叭"] },
        { "squeezer", ["400", "开瓶喷泉枪", "香槟", "酒桶"] },
        { "foil-squeezer", ["401", "开瓶喷泉枪金属箔", "贴牌香槟", "贴牌酒桶", "金箔"] },
        { "jet-squelcher", ["90", "喷射清洁枪", "蓝管"] },
        { "custom-jet-squelcher", ["91", "喷射清洁枪改装", "贴牌蓝管"] },
        { "splattershot", ["40", "斯普拉射击枪", "小绿"] },
        { "tentatek-splattershot", ["41", "斯普拉射击枪联名", "贴牌小绿", "小粉"] },
        { "splattershot-nova", ["100", "太空射击枪", "大绿", "太空枪"] },
        { "annaki-splattershot-nova", ["101", "太空射击枪联名", "贴牌太空枪", "飞机启动器"] },
        { "splattershot-jr", ["10", "新叶射击枪", "新叶"] },
        { "splash-o-matic", ["20", "窄域标记枪", "针管", "针枪"] },
        { "neo-splash-o-matic", ["21", "窄域标记枪新型", "贴牌针管", "贴牌针枪"] },
        { "aerospray-mg", ["30", "专业模型枪MG", "银喷"] },
        { "aerospray-rg", ["31", "专业模型枪RG", "金喷"] },
        { "h-3-nozzlenose", ["310", "H3卷管枪", "H3"] },
        { "h-3-nozzlenose-d", ["311", "H3卷管枪D", "H3D"] },
        { "l-3-nozzlenose", ["300", "L3卷管枪", "L3"] },
        { "l-3-nozzlenose-d", ["301", "L3卷管枪D", "L3D"] },
        { "n-zap-85", ["60", "N-ZAP85", "85", "ZAP"] },
        { "n-zap-89", ["61", "N-ZAP89", "89", "红ZAP", "贴牌ZAP"] },
        { "clash-blaster", ["230", "冲涂爆破枪", "蜡笔炮", "脑干切除枪", "脑干切除炮"] },
        { "clash-blaster-neo", ["231", "冲涂爆破枪新型", "贴牌蜡笔炮"] },
        { "blaster", ["210", "火热爆破枪", "热炮"] },
        { "custom-blaster", ["211", "火热爆破枪改装", "贴牌热炮"] },
        { "rapid-blaster", ["240", "快速爆破枪", "红炮"] },
        { "rapid-blaster-pro", ["250", "快速爆破枪精英", "长红炮"] },
        { "rapid-blaster-pro-deco", ["251", "快速爆破枪精英装饰", "长蓝泡", "贴牌长红炮"] },
        { "rapid-blaster-deco", ["241", "快速爆破枪装饰", "蓝泡", "贴牌红炮"] },
        { "luna-blaster", ["200", "新星爆破枪", "白炮", "NOVA", "NOVA炮"] },
        { "luna-blaster-neo", ["201", "新星爆破枪新型", "黑炮", "贴牌白炮"] },
        { "range-blaster", ["220", "远距爆破枪", "长热泡"] },
        { "s-blast-92", ["260", "S-BLAST92", "SB炮", "92", "92炮"] },
        { "s-blast-91", ["261", "S-BLAST91", "贴牌SB炮", "91", "91炮"] },
        { "dynamo-roller", ["1020", "电动马达滚筒", "重刷", "银重刷"] },
        { "gold-dynamo-roller", ["1021", "电动马达滚筒高磁波", "金重刷", "贴牌重刷"] },
        { "flingza-roller", ["1030", "可变式滚筒", "钢笔", "钢笔刷"] },
        { "foil-flingza-roller", ["1031", "可变式滚筒金属箔", "贴牌钢笔", "贴牌钢笔刷"] },
        { "big-swig-roller", ["1040", "宽滚筒", "宽刷", "阿宽"] },
        { "big-swig-roller-express", ["1041", "宽滚筒联名", "贴牌宽刷"] },
        { "splat-roller", ["1010", "斯普拉滚筒", "中刷"] },
        { "krak-on-splat-roller", ["1011", "斯普拉滚筒联名", "贴牌中刷"] },
        { "carbon-roller", ["1000", "碳纤维滚筒", "碳刷", "轻滚"] },
        { "carbon-roller-deco", ["1001", "碳纤维滚筒装饰", "贴牌碳刷"] },
        { "inkbrush", ["1100", "巴勃罗", "小笔刷"] },
        { "inkbrush-nouveau", ["1101", "巴勃罗新艺术", "巴勃罗新艺术", "贴牌小笔刷", "贴牌巴勃罗"] },
        { "octobrush", ["1110", "北斋"] },
        { "octobrush-nouveau", ["1111", "北斋新艺术", "北斋新艺术", "贴牌北斋"] },
        { "painbrush", ["1120", "文森", "重笔"] },
        { "painbrush-nouveau", ["1121", "文森新艺术", "贴牌文森"] },
        { "bamboozler-14-mk-i", ["2050", "14式竹筒枪甲", "竹子", "竹筒", "竹狙"] },
        { "e-liter-4k-scope", ["2040", "4K准星枪", "镜4K", "镜4"] },
        { "custom-e-liter-4k-scope", ["2041", "4K准星枪改装", "贴牌镜4K", "贴牌镜4"] },
        { "goo-tuber", ["2060", "高压油管枪", "水管"] },
        { "custom-goo-tuber", ["2061", "高压油管枪改装", "贴牌水管"] },
        { "e-liter-4k", ["2030", "公升4K", "4K"] },
        { "custom-e-liter-4k", ["2031", "公升4K改装", "贴牌4K"] },
        { "splat-charger", ["2010", "斯普拉蓄力狙击枪", "绿狙"] },
        { "zf-splat-charger", ["2011", "斯普拉蓄力狙击枪联名", "贴牌绿狙", "红狙"] },
        { "splatterscope", ["2020", "斯普拉准星枪", "镜绿狙"] },
        { "zf-splatterscope", ["2021", "斯普拉准星枪联名", "贴牌镜绿狙", "贴牌红狙"] },
        { "classic-squiffer", ["2000", "鱿快洁α", "鱿快洁", "洗洁精", "速狙", "轻狙"] },
        { "new-squiffer", ["2001", "鱿快洁β", "贴牌鱿快洁", "贴牌洗洁精", "洗洁精β", "贴牌速狙", "贴牌轻狙"] },
        { "snipewriter-5h", ["2070", "RPEN5H", "铅笔", "铅笔狙"] },
        { "snipewriter-5b", ["2071", "RPEN5B", "贴牌铅笔", "贴牌铅笔狙"] },
        { "explosher", ["3040", "爆炸泼桶", "重桶"] },
        { "custom-explosher", ["3041", "爆炸泼桶改装", "贴牌重桶"] },
        { "slosher", ["3000", "飞溅泼桶", "红桶", "紫桶"] },
        { "slosher-deco", ["3001", "飞溅泼桶装饰", "贴牌红桶"] },
        { "sloshing-machine", ["3020", "回旋泼桶", "洗衣机"] },
        { "sloshing-machine-neo", ["3021", "回旋泼桶新型", "贴牌洗衣机"] },
        { "bloblobber", ["3030", "满溢泡澡泼桶", "浴缸", "泡澡桶", "泡泡桶"] },
        { "bloblobber-deco", ["3031", "满溢泡澡泼桶装饰", "贴牌浴缸", "贴牌泡澡桶", "贴牌泡泡桶"] },
        { "dread-wringer", ["3050", "墨瀑淋", "拖把桶", "拖把", "拖布桶", "拖布"] },
        { "dread-wringer-d", ["3051", "墨瀑淋D", "贴牌拖把桶", "贴牌拖把", "贴牌拖布桶", "贴牌拖布"] },
        { "tri-slosher", ["3010", "洗笔桶", "绿桶", "蓝桶"] },
        { "tri-slosher-nouveau", ["3011", "洗笔桶新艺术", "洗笔桶新艺术", "贴牌绿桶", "贴牌蓝桶"] },
        { "heavy-edit-splatling", ["4050", "审查者", "红笔"] },
        { "mini-splatling", ["4000", "斯普拉旋转枪", "轻加"] },
        { "zink-mini-splatling", ["4001", "斯普拉旋转枪联名", "贴牌轻加"] },
        { "heavy-splatling", ["4010", "桶装旋转枪", "中加"] },
        { "heavy-splatling-deco", ["4011", "桶装旋转枪装饰", "贴牌中加"] },
        { "hydra-splatling", ["4020", "消防栓旋转枪", "消防栓", "栓", "栓子"] },
        { "nautilus-47", ["4040", "鹦鹉螺号47", "鹦鹉螺", "鹦鹉螺47", "47"] },
        { "nautilus-79", ["4041", "鹦鹉螺号79", "鹦鹉螺79", "贴牌鹦鹉螺", "79"] },
        { "ballpoint-splatling", ["4030", "圆珠笔"] },
        { "ballpoint-splatling-nouveau", ["4031", "圆珠笔新艺术", "圆珠笔新艺术", "贴牌圆珠笔"] },
        { "dapple-dualies", ["5000", "溅镀枪", "牙刷", "红牙刷", "红牙"] },
        { "dapple-dualies-nouveau", ["5001", "溅镀枪新艺术", "溅镀枪新艺术", "蓝牙刷", "贴牌牙刷", "蓝牙"] },
        { "glooga-dualies", ["5020", "开尔文525", "525", "蓝525"] },
        { "glooga-dualies-deco", ["5021", "开尔文525装饰", "贴牌525", "黄525"] },
        { "douser-dualies-ff", ["5050", "灭熄FF", "长红双", "灭火双"] },
        { "dualie-squelchers", ["5030", "双重清洁枪", "红双"] },
        { "custom-dualie-squelchers", ["5031", "双重清洁枪改装", "贴牌红双"] },
        { "splat-dualies", ["5010", "斯普拉机动枪", "绿双"] },
        { "enperry-splat-dualies", ["5011", "斯普拉机动枪联名", "贴牌绿双", "金双"] },
        { "light-tetra-dualies", ["5041", "四重弹跳手枪白", "贴牌气垫", "白气垫"] },
        { "dark-tetra-dualies", ["5040", "四重弹跳手枪黑", "气垫", "黑气垫"] },
        { "recycled-brella-24-mk-i", ["6030", "24式可替换伞甲", "竹伞"] },
        { "tenta-brella", ["6010", "露营防空伞", "重伞", "大伞"] },
        { "tenta-sorella-brella", ["6011", "露营防空伞姐妹", "贴牌重伞", "姐妹", "姐妹伞"] },
        { "undercover-brella", ["6020", "特工配件", "间谍伞", "特工伞"] },
        { "undercover-sorella-brella", ["6021", "特工配件姐妹", "贴牌间谍伞", "贴牌特工伞"] },
        { "splat-brella", ["6000", "遮阳防空伞", "中伞"] },
        { "sorella-brella", ["6001", "遮阳防空伞姐妹", "贴牌中伞"] },
        { "tri-stringer", ["7010", "三发猎鱼弓", "长弓", "三发弓", "猎鱼弓"] },
        { "inkline-tri-stringer", ["7011", "三发猎鱼弓联名", "贴牌长弓", "贴牌三发弓", "贴牌猎鱼弓"] },
        { "reef-lux-450", ["7020", "LACT450", "短弓"] },
        { "reef-lux-450-deco", ["7021", "LACT450装饰", "贴牌短弓"] },
        { "splatana-stamper", ["8000", "工作刮水刀", "电锯"] },
        { "splatana-stamper-nouveau", ["8001", "工作刮水刀新艺术", "贴牌电锯"] },
        { "splatana-wiper", ["8010", "雨刷刮水刀", "刮水刀"] },
        { "splatana-wiper-deco", ["8011", "雨刷刮水刀装饰", "贴牌刮水刀"] },
    };

    /// <summary>
    ///     Suite build adopt game mode
    /// </summary>
    public static Dictionary<string, string> BuildAdoptModes = new()
    {
        { "SZ", "区域" },
        { "TC", "塔楼" },
        { "RM", "鱼虎" },
        { "CB", "蛤蜊" },
    };
}
