namespace Jellyfish.Client.SendouInk.Core;

/// <summary>
///     API Constants
/// </summary>
public static class Constants
{
    /// <summary>
    ///     Weapon slugs (API) as key, alias as values
    ///     Please use uppercase and remove white chars for matching alias
    /// </summary>
    public static Dictionary<string, string[]> WeaponSlugs = new()
    {
        { "52-gal", new[] { "50", ".52加仑", "52" } },
        { "96-gal", new[] { "80", ".96加仑", "96" } },
        { "96-gal-deco", new[] { "81", ".96加仑装饰", "贴牌96" } },
        { "splattershot-pro", new[] { "70", "顶尖射击枪", "精英枪", "蓝精英" } },
        { "forge-splattershot-pro", new[] { "71", "顶尖射击枪联名", "贴牌精英枪", "黄精英" } },
        { "custom-splattershot-jr", new[] { "11", "枫叶射击枪", "枫叶" } },
        { "sploosh-o-matic", new[] { "0", "广域标记枪", "喇叭" } },
        { "neo-sploosh-o-matic", new[] { "1", "广域标记枪新型", "贴牌喇叭" } },
        { "squeezer", new[] { "400", "开瓶喷泉枪", "香槟", "酒桶" } },
        { "jet-squelcher", new[] { "90", "喷射清洁枪", "蓝管" } },
        { "custom-jet-squelcher", new[] { "91", "喷射清洁枪改装", "贴牌蓝管" } },
        { "splattershot", new[] { "40", "斯普拉射击枪", "小绿" } },
        { "tentatek-splattershot", new[] { "41", "斯普拉射击枪联名", "贴牌小绿", "小粉" } },
        { "splattershot-nova", new[] { "100", "太空射击枪", "大绿", "太空枪" } },
        { "annaki-splattershot-nova", new[] { "101", "太空射击枪联名", "贴牌太空枪", "飞机启动器" } },
        { "splattershot-jr", new[] { "10", "新叶射击枪", "新叶" } },
        { "splash-o-matic", new[] { "20", "窄域标记枪", "针管", "针枪" } },
        { "neo-splash-o-matic", new[] { "21", "窄域标记枪新型", "贴牌针管", "贴牌针枪" } },
        { "aerospray-mg", new[] { "30", "专业模型枪MG", "银喷" } },
        { "aerospray-rg", new[] { "31", "专业模型枪RG", "金喷" } },
        { "h-3-nozzlenose", new[] { "310", "H3卷管枪", "H3" } },
        { "h-3-nozzlenose-d", new[] { "311", "H3卷管枪D", "H3D" } },
        { "l-3-nozzlenose", new[] { "300", "L3卷管枪", "L3" } },
        { "l-3-nozzlenose-d", new[] { "301", "L3卷管枪D", "L3D" } },
        { "n-zap-85", new[] { "60", "N-ZAP85", "85", "ZAP" } },
        { "n-zap-89", new[] { "61", "N-ZAP89", "89", "红ZAP", "贴牌ZAP" } },
        { "clash-blaster", new[] { "230", "冲涂爆破枪", "蜡笔炮", "脑干切除枪", "脑干切除炮" } },
        { "clash-blaster-neo", new[] { "231", "冲涂爆破枪新型", "贴牌蜡笔炮" } },
        { "blaster", new[] { "210", "火热爆破枪", "热炮" } },
        { "rapid-blaster", new[] { "240", "快速爆破枪", "红炮" } },
        { "rapid-blaster-pro", new[] { "250", "快速爆破枪精英", "长红炮" } },
        { "rapid-blaster-pro-deco", new[] { "251", "快速爆破枪精英装饰", "长蓝泡", "贴牌长红炮" } },
        { "rapid-blaster-deco", new[] { "241", "快速爆破枪装饰", "蓝泡", "贴牌红炮" } },
        { "luna-blaster", new[] { "200", "新星爆破枪", "白炮", "NOVA", "NOVA炮" } },
        { "luna-blaster-neo", new[] { "201", "新星爆破枪新型", "黑炮", "贴牌白炮" } },
        { "range-blaster", new[] { "220", "远距爆破枪", "长热泡" } },
        { "s-blast-92", new[] { "260", "S-BLAST92", "SB炮", "92", "92炮" } },
        { "dynamo-roller", new[] { "1020", "电动马达滚筒", "重刷", "银重刷" } },
        { "gold-dynamo-roller", new[] { "1021", "电动马达滚筒高磁波", "金重刷", "贴牌重刷" } },
        { "flingza-roller", new[] { "1030", "可变式滚筒", "钢笔", "钢笔刷" } },
        { "big-swig-roller", new[] { "1040", "宽滚筒", "宽刷", "阿宽" } },
        { "big-swig-roller-express", new[] { "1041", "宽滚筒联名", "贴牌宽刷" } },
        { "splat-roller", new[] { "1010", "斯普拉滚筒", "中刷" } },
        { "krak-on-splat-roller", new[] { "1011", "斯普拉滚筒联名", "贴牌中刷" } },
        { "carbon-roller", new[] { "1000", "碳纤维滚筒", "碳刷", "轻滚" } },
        { "carbon-roller-deco", new[] { "1001", "碳纤维滚筒装饰", "贴牌碳刷" } },
        { "inkbrush", new[] { "1100", "巴勃罗", "小笔刷" } },
        { "inkbrush-nouveau", new[] { "1101", "巴勃罗·新艺术", "巴勃罗新艺术", "贴牌小笔刷", "贴牌巴勃罗" } },
        { "octobrush", new[] { "1110", "北斋" } },
        { "octobrush-nouveau", new[] { "1111", "北斋·新艺术", "北斋新艺术", "贴牌北斋" } },
        { "painbrush", new[] { "1120", "文森", "重笔" } },
        { "bamboozler-14-mk-i", new[] { "2050", "14式竹筒枪·甲", "竹子", "竹筒", "竹狙" } },
        { "e-liter-4k-scope", new[] { "2040", "4K准星枪", "镜4K" } },
        { "goo-tuber", new[] { "2060", "高压油管枪", "水管" } },
        { "custom-goo-tuber", new[] { "2061", "高压油管枪改装", "贴牌水管" } },
        { "e-liter-4k", new[] { "2030", "公升4K", "4K" } },
        { "splat-charger", new[] { "2010", "斯普拉蓄力狙击枪", "绿狙" } },
        { "zf-splat-charger", new[] { "2011", "斯普拉蓄力狙击枪联名", "贴牌绿狙", "红狙" } },
        { "splatterscope", new[] { "2020", "斯普拉准星枪", "镜绿狙" } },
        { "zf-splatterscope", new[] { "2021", "斯普拉准星枪联名", "贴牌镜绿狙", "贴牌红狙" } },
        { "classic-squiffer", new[] { "2000", "鱿快洁α", "鱿快洁", "洗洁精", "速狙", "轻狙" } },
        { "snipewriter-5h", new[] { "2070", "R-PEN/5H", "铅笔", "铅笔狙" } },
        { "explosher", new[] { "3040", "爆炸泼桶", "重桶" } },
        { "slosher", new[] { "3000", "飞溅泼桶", "红桶", "紫桶" } },
        { "slosher-deco", new[] { "3001", "飞溅泼桶装饰", "贴牌红桶" } },
        { "sloshing-machine", new[] { "3020", "回旋泼桶", "洗衣机" } },
        { "sloshing-machine-neo", new[] { "3021", "回旋泼桶新型", "贴牌洗衣机" } },
        { "bloblobber", new[] { "3030", "满溢泡澡泼桶", "浴缸", "泡澡桶", "泡泡桶" } },
        { "bloblobber-deco", new[] { "3031", "满溢泡澡泼桶装饰", "贴牌浴缸", "贴牌泡澡桶", "贴牌泡泡桶" } },
        { "dread-wringer", new[] { "3050", "墨瀑淋", "拖把桶", "拖把", "拖布桶", "拖布" } },
        { "tri-slosher", new[] { "3010", "洗笔桶", "绿桶", "蓝桶" } },
        { "tri-slosher-nouveau", new[] { "3011", "洗笔桶·新艺术", "洗笔桶新艺术", "贴牌绿桶", "贴牌蓝桶" } },
        { "heavy-edit-splatling", new[] { "4050", "审查者", "红笔" } },
        { "mini-splatling", new[] { "4000", "斯普拉旋转枪", "轻加" } },
        { "zink-mini-splatling", new[] { "4001", "斯普拉旋转枪联名", "贴牌轻加" } },
        { "heavy-splatling", new[] { "4010", "桶装旋转枪", "中加" } },
        { "heavy-splatling-deco", new[] { "4011", "桶装旋转枪装饰", "贴牌中加" } },
        { "hydra-splatling", new[] { "4020", "消防栓旋转枪", "消防栓", "栓", "栓子" } },
        { "nautilus-47", new[] { "4040", "鹦鹉螺号47", "鹦鹉螺" } },
        { "ballpoint-splatling", new[] { "4030", "圆珠笔" } },
        { "ballpoint-splatling-nouveau", new[] { "4031", "圆珠笔·新艺术", "圆珠笔新艺术", "贴牌圆珠笔" } },
        { "dapple-dualies", new[] { "5000", "溅镀枪", "牙刷", "红牙刷", "红牙" } },
        { "dapple-dualies-nouveau", new[] { "5001", "溅镀枪·新艺术", "溅镀枪新艺术", "蓝牙刷", "贴牌牙刷", "蓝牙" } },
        { "glooga-dualies", new[] { "5020", "开尔文525", "525" } },
        { "dualie-squelchers", new[] { "5030", "双重清洁枪", "红双" } },
        { "custom-dualie-squelchers", new[] { "5031", "双重清洁枪改装", "贴牌红双" } },
        { "splat-dualies", new[] { "5010", "斯普拉机动枪", "绿双" } },
        { "light-tetra-dualies", new[] { "5041", "四重弹跳手枪白", "贴牌气垫", "白气垫" } },
        { "dark-tetra-dualies", new[] { "5040", "四重弹跳手枪黑", "气垫", "黑气垫" } },
        { "tenta-brella", new[] { "6010", "露营防空伞", "重伞", "大伞" } },
        { "tenta-sorella-brella", new[] { "6011", "露营防空伞姐妹", "贴牌重伞", "姐妹", "姐妹伞" } },
        { "undercover-brella", new[] { "6020", "特工配件", "间谍伞", "特工伞" } },
        { "splat-brella", new[] { "6000", "遮阳防空伞", "中伞" } },
        { "sorella-brella", new[] { "6001", "遮阳防空伞姐妹", "贴牌中伞" } },
        { "tri-stringer", new[] { "7010", "三发猎鱼弓", "长弓", "三发弓", "猎鱼弓" } },
        { "inkline-tri-stringer", new[] { "7011", "三发猎鱼弓联名", "贴牌长弓", "贴牌三发弓", "贴牌猎鱼弓" } },
        { "reef-lux-450", new[] { "7020", "LACT-450", "短弓" } },
        { "splatana-stamper", new[] { "8000", "工作刮水刀", "电锯" } },
        { "splatana-wiper", new[] { "8010", "雨刷刮水刀", "刮水刀" } },
        { "splatana-wiper-deco", new[] { "8011", "雨刷刮水刀装饰", "贴牌刮水刀" } },
    };
}
