version: '3.5'

services:
  postgres:
    container_name: jellyfish_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: jellyfish
      POSTGRES_PASSWORD: <password>
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
